### ISSUE TITLE
Handles work fine, but more then 2 and the responses fail to come trough. Code within Def does get triggered.

### ISSUE THREAD

**Issue by TipsyTrex** [gabrielebarola/telegram-upy#13]
If I add more then 2 handles the auto reply only works for the first 2. The rest of the code gets run but the reply does not get send out.

**Comment by gabrielebarola** [comment]
Hi, can you please post the code you're trying to run?

**Comment by TipsyTrex** [comment]
I've rewriten the code and for some reason it seems to work fine now. While in the testing phase i encountered the problem, which is odd since the commands have not changed. i onlyt added digital pin outputs. If it pops up again i'll post the code that is causing issues. for now, case closed. Thanks for the awesome work :)
