### ISSUE TITLE
Message Handler is not working

### ISSUE THREAD

**Issue by thycoding** [gabrielebarola/telegram-upy#9]
Hi,

The message handler is not working:

@bot.add_message_handler('^Hi')
def hello(update):
    update.reply('hello')

**Comment by gabrielebarola** [comment]
Hi, can you provide more context? For example the entire source code, the mcu you are using as well as if other examples work.

**Comment by thycoding** [comment]
I am using a ESP32 WROOM and my program is as followng:

from utelegram import Bot
from machine import Pin

TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxx'

bot = Bot(TOKEN)
led = Pin(2, Pin.OUT)

@bot.add_command_handler('help')
def help(update):
    update.reply('Write on to power the led on \nWrite off to power the led off \nWrite /value to retrieve the current status of the led')

@bot.add_command_handler('value')
def value(update):
    if led.value():
        update.reply('LED is on')
    else:
        update.reply('LED is off')

@bot.add_message_handler('^on|On|ON$')
def on(update):
    led.on()

@bot.add_message_handler('^off|Off|OFF$')
def off(update):
    led.off()

@bot.add_message_handler('^Hi')
def hello(update):
    update.reply('hello')

bot.start_loop()

**Comment by thycoding** [comment]
from utelegram import Bot
from machine import Pin

TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxx'

bot = Bot(TOKEN)
led = Pin(2, Pin.OUT)

@bot.add_command_handler('help')
def help(update):
    update.reply('Write on to power the led on \nWrite off to power the led off \nWrite /value to retrieve the current status of the led')

@bot.add_command_handler('value')
def value(update):
    if led.value():
        update.reply('LED is on')
    else:
        update.reply('LED is off')

@bot.add_message_handler('^on|On|ON$')
def on(update):
    led.on()

@bot.add_message_handler('^off|Off|OFF$')
def off(update):
    led.off()

@bot.add_message_handler('^Hi')
def hello(update):
    update.reply('hello')

bot.start_loop()

**Comment by thycoding** [comment]
I am using a ESP32 WROOM.  The source code is as following:

from utelegram import Bot
from machine import Pin

TOKEN = 'xxxxxxxxxxxxxxxxxxxxxxxx'

bot = Bot(TOKEN)
led = Pin(2, Pin.OUT)

@bot.add_command_handler('help')
def help(update):
update.reply('Write on to power the led on \nWrite off to power the led off \nWrite /value to retrieve the current status of the led')

@bot.add_command_handler('value')
def value(update):
if led.value():
update.reply('LED is on')
else:
update.reply('LED is off')

@bot.add_message_handler('^on|On|ON$')
def on(update):
led.on()

@bot.add_message_handler('^off|Off|OFF$')
def off(update):
led.off()

@bot.add_message_handler('^Hi')
def hello(update):
update.reply('hello')

bot.start_loop()

**Comment by gabrielebarola** [comment]
There is no indentation in your code, is that right?

**Comment by thycoding** [comment]
There is indentation. I modified the program from the examples
